version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: production
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - zukii-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - zukii-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  zukii-network:
    name: zukii-network 